# Generated by Django 6.0.1 on 2026-01-21 00:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="piano",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="piano",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piano",
            name="condition",
            field=models.CharField(
                choices=[("new", "New"), ("used", "Used")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="piano",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="piano",
            name="price",
            field=models.IntegerField(),
        ),
    ]
